name: defualt
# 
path: defualt
img_res_h: 32
img_res_w: 32
img_input_channels: 1
img_cond_channels: 1

class_name: training.dataset_cond.CondDataset

# data  aug
xflip: True
yflip: True

# peformance
cache: True

# place holder 
max_size: null