defaults:
  - default
  - _self_

name: test_dataset
# 
# path: data/test_data/snaps
path: data/test_data/test_data.zip
img_res_h: 128
img_res_w: 64
img_input_channels: 2
img_cond_channels: 10

class_name: training.dataset_cond.CondDataset
