# @package _global_
defaults:
  - override /dataset_kwargs: default
  - override /network_kwargs: default

# some comment settings
# ========================
# Main options
# ========================
outdir: outputs       # Where to save the results

# ========================
# Training related
# ========================
duration: 200         # Training duration in MIMG (million images)
batch: 512            # Total batch size across all GPUs
batch_gpu: null       # Limit batch size per GPU
optimizer_kwargs:
  class_name: torch.optim.Adam
  lr: 0.001    # Learning rate


# ========================
# I/O-related
# ========================
tick: 50              # How often to print progress (in KIMG)
snap: 50              # How often to save snapshots (in ticks)
dump: 500             # How often to dump training state (in ticks)
dry_run: true        # Print training options and exit

