defaults:
  - default
  - _self_

# model setting
model_name: ncsnpp
model_type: SongUNet
embedding_type: fourier
encoder_type: residual
decoder_type: standard
channel_mult_noise: 2
resample_filter: [1,3,3,1]
model_channels: 128
channel_mult: [2, 2, 2]