defaults:
  - default
  - _self_

# model setting 
model_name: tiny
model_type: SongUNet
embedding_type: positional
encoder_type: standard
decoder_type: standard
channel_mult_noise: 1
resample_filter: [1, 1]
model_channels: 64
channel_mult: [1, 1]
