defaults:
  - default
  - _self_

model_name: tiny
# model settings
model_channels: 32              # Base multiplier for the number of channels.
channel_mult: [1,1]           # Per-resolution multipliers for the number of channels.
channel_mult_emb: 2               # Multiplier for the dimensionality of the embedding vector.
num_blocks: 1                     # Number of residual blocks per resolution.
attn_resolutions: [8]            # List of resolutions with self-attention.
