# configs/main.yaml (or conf/main.yaml)
defaults:
  - _self_
  - runs: test_run

outdir: output
# Default global settings from EDM paper
total_kimg: 200000
ema_halflife_kimg: 500
batch_size: 512
batch_gpu: None
loss_scaling: 1.0
cudnn_benchmark: True
kimg_per_tick: 50
snapshot_ticks: 50
state_dump_ticks: 500
seed: 123456789


loss_kwargs:
  class_name: training.loss.EDMLoss


optimizer_kwargs:
  class_name: torch.optim.Adam
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-08

network_kwargs:
  class_name: training.networks.EDMPrecond
  dropout: 0.13
  use_fp16: False

data_loader_kwargs:
  pin_memory: True
  num_workers: 1
  prefetch_factor: 2